
- hosts: web
  vars:
    packages:
      - git
      # - pm2
      - nodejs
      - nginx
    repo: https://github.com/fropa/nodejs-hello
    user: david
    appPath: /tmp/server/app.js
  roles:
    - role : createuser
    - role : packages
    - role : clonerepo
    - role : startserver
    - role : startnginx

