    - name: Install pm2 service for automation nodejs
      npm:
        name: pm2
        global: yes
        state: latest

    - name: Create dir for app
      file:
        path: /opt/nodejs
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"


    - name: Copy app files
      copy:
        src: /etc/ansible/files/app.js
        dest: /opt/nodejs/app.js
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644

    - name: Set httpd permission for nginx
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Start nodejs app, by pm2 (nonidempotent)
      become: yes
      #become_user: "{{ user }}"
      command: /usr/local/bin/pm2 list
      #      command: /usr/local/bin/pm2 start {{ appPath }}
      register: stat


    - name: show the start status
      debug: var=stat

